# Generated by Django 4.2.1 on 2023-06-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_inventory_product_supplier_productvariation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='city',
        ),
        migrations.RemoveField(
            model_name='inventoryproduct',
            name='inventoryId',
        ),
        migrations.RemoveField(
            model_name='inventoryproduct',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cityId',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='cityId',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='productId',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='InventoryProduct',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductVariation',
        ),
    ]
