# Generated by Django 4.2 on 2023-06-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_category_alter_city_name_alter_inventory_cityid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='pvType',
        ),
        migrations.AlterField(
            model_name='product',
            name='cityId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.city', verbose_name='City Id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pType',
            field=models.CharField(max_length=200, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
