# Generated by Django 4.2 on 2023-06-27 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_product_ptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productvariation', verbose_name='Category Name'),
        ),
    ]
