# Generated by Django 4.2 on 2023-06-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_supplier_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='SOME STRING', max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phoneNum',
            field=models.CharField(default='+98123456789', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
