# Generated by Django 4.2 on 2023-06-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_supplier_address_supplier_email_supplier_phonenum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
