# Generated by Django 4.2 on 2023-06-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_supplier_address_alter_supplier_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='name',
        ),
        migrations.AddField(
            model_name='supplier',
            name='LastName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='firstName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phoneNum',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
