# Generated by Django 4.2 on 2023-06-29 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_order_product_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='LastName',
            new_name='lastName',
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.inventoryproduct'),
        ),
    ]
