# Generated by Django 4.2 on 2023-07-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_rename_lastname_supplier_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alt', models.CharField(max_length=200)),
                ('imageUrl', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
