# Generated by Django 4.2 on 2023-07-01 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_product_image_productvariation_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('h', models.CharField(max_length=200)),
                ('p', models.TextField(max_length=400)),
                ('image', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='shop.image')),
            ],
        ),
    ]
